FROM golang:1.26-alpine

RUN apk add --no-cache npm git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY shared/ /app/shared/
RUN cd shared && go mod download

COPY services/auth/ /app/services/auth/
RUN cd services/auth && go mod download

CMD sh -c "cd /app/services/auth && air"
