FROM golang:1.26-alpine

RUN apk add --no-cache npm git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY shared/ /app/shared/
RUN cd shared && go mod download

COPY services/game/ /app/services/game/
RUN cd services/game && go mod download

CMD sh -c "cd /app/services/game && air"
