definitions:
  types.LoginRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  types.LoginResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Name and password
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login response with token if successful
          schema:
            $ref: '#/definitions/types.LoginResponse'
      summary: Login
      tags:
      - auth
swagger: "2.0"
