FROM golang:1.26-alpine

RUN apk add --no-cache nodejs npm git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY shared/ /app/shared/
RUN cd shared && go mod download

COPY services/gateway/backend/ /app/services/gateway/backend/
RUN cd services/gateway/backend && go mod download

COPY services/gateway/frontend/ /app/services/gateway/frontend/
RUN cd services/gateway/frontend && npm ci

CMD sh -c "cd /app/services/gateway/frontend && npm run watch & cd /app/services/gateway/backend && air"
